name: CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  publish:
    strategy:
      matrix:
        dir: [ sql ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: publish
        name: Publish ${{ matrix.dir }}
        shell: bash
        run: |
          set -e

          CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          if [[ "${CURRENT_BRANCH}" != "main" ]]; then
            echo 'This action can only be run on main branch!' 1>&2
            exit 1
          fi

          cd ${{ matrix.dir }}
          npm ci
          PACKAGE_VERSION="$(cat package.json | jq -rM .version)"
          npm install --no-save @jsdevtools/npm-publish
          ./node_modules/.bin/npm-publish --access public --token '${{ secrets.NPM_TOKEN }}'

          # TODO we must generate release notes for the package
          # TODO set up organization-wide CICD-GitHub account
          GIT_TAG_NAME="${{ matrix.dir }}-v${PACKAGE_VERSION}"
          git config --global user.email "cd-automation@dataheaving.project"
          git config --global user.name "CD Automation"
          git tag \
            -a \
            -m "Component ${{ matrix.dir }} release ${PACKAGE_VERSION}" \
            "${GIT_TAG_NAME}"
          git push origin "${GIT_TAG_NAME}"
